version: "3.2"
services:
  web1:
    # replace username/repo:tag with your name and image details
    image: megadock/apache:1.0
    volumes:
#      - type: volume
#        source: apache-volume:/Apache/httpd
#        target: /etc/httpd
      - ./Apache/httpd:/etc/httpd 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:80"

  web2:
    # replace username/repo:tag with your name and image details
    image: megadock/nginx:1.0
    volumes:
#      - type: volume
#        source: nginx-volume:/Nginx/nginx
#        target: /etc/nginx
      - ./Nginx/nginx:/etc/nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9001:80"
   
#volumes:
#  apache-volume:
#  nginx-volume:
  

